### ISSUE TITLE
Missing jQuery UI widget

### ISSUE THREAD

**Issue by linusblom** [chas-academy/07-trello-clone-idaenglund#1]
As part of the requirements for this assignment you need to supply a basic implementation of either a) a plugin/widget using the jQuery UI Widget factory or b) the jQuery plugin factory.

Please refer to one of the patterns that are defined and available in this repository:

* https://github.com/jquery-boilerplate/jquery-patterns

Extra note: The plugin doesn't have to be that complex, just toggle some CSS property or manipulate the selector in the DOM somehow, text or similar.

**Comment by idaenglund** [comment]
Thank you Linus (sorry for calling you Pontus) Now there is a widget :-) A blue one!
